version: 0.2

env:
  variables:    
    ORG: "Uon-Social"
    REPO_TO_SCAN: "Backend"    
  secrets-manager:
    GIT_TOKEN: "arn:aws:secretsmanager:us-east-1:636184159442:secret:james-test-WYYiCZ:GIT_TOKEN"
    DOCKER_USERNAME: "arn:aws:secretsmanager:us-east-1:636184159442:secret:james-test-WYYiCZ:DOCKER_USERNAME"
    DOCKER_PASSWORD: "arn:aws:secretsmanager:us-east-1:636184159442:secret:james-test-WYYiCZ:DOCKER_PASSWORD"


phases:
  install:
    on-failure: ABORT

  pre_build:    
    commands:
      - echo "Running Trufflehog scanning for secrets ..."
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - git clone https://$GIT_TOKEN@github.com/$ORG/$REPO_TO_SCAN.git
      - docker run -v $PWD:/projects trufflesecurity/trufflehog:latest git file:///projects --only-verified --max-depth=1 --json > trufflehog.log
      - echo "Trufflehog scanning complete"
      - echo "Identified Issues ..."
      - |
        while IFS= read -r line
        do
          echo "$line" | jq -r '.SourceMetadata.Data.Git'
        done < "trufflehog.log"
          
artifacts:
  files:
    - trufflehog.json