version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install Dependencies"
      - apt-get update 
      - apt-get install -y wget
      - apt-get install -y fontconfig libstdc++