version: 0.2

env:
  variables:    
    GIT_USER: "jamesTepia"
    GIT_REPO: "test-repo"    
    AWS_DEFAULT_REGION: "us-east-1"
    REPO_TO_SCAN: "Uon-Social/Backend"
  secrets-manager:
    GIT_TOKEN: "arn:aws:secretsmanager:us-east-1:636184159442:secret:james-test-WYYiCZ:GIT_TOKEN"
    DOCKER_USERNAME: "arn:aws:secretsmanager:us-east-1:636184159442:secret:james-test-WYYiCZ:DOCKER_USERNAME"
    DOCKER_PASSWORD: "arn:aws:secretsmanager:us-east-1:636184159442:secret:james-test-WYYiCZ:DOCKER_PASSWORD"


phases:
  install:
    on-failure: ABORT    

  pre_build:
    commands:
      - echo "Running Trufflehog scanning for secrets ..."      
      - git clone https://$GIT_TOKEN@github.com/$REPO_TO_SCAN.git
      - cd $REPO_TO_SCAN
      - git checkout $CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker run -v "$(pwd):/project" trufflesecurity/trufflehog:latest file:///project --token $GIT_TOKEN --no-verification --json > trufflehog.log
      - echo "Trufflehog scanning complete"
      - echo "Identified Issues ..."
      - |
        while IFS= read -r line
        do
          echo "$line" | jq -r '.SourceMetadata.Data.Github.link'
        done < "trufflehog.log"
          
artifacts:
  files:
    - trufflehog.json