version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      docker: ubuntu@latest
    commands:
      - echo "Install Dependencies"
      - apt-get update 
      - apt-get install -y wget
      - apt-get install -y fontconfig freetype freetype-devel fontconfig-devel libstdc++
