version: 0.2

env:
  variables:    
    GIT_USER: "jamesTepia"
    GIT_REPO: "test-repo"    
    AWS_DEFAULT_REGION: "us-east-1"
  secrets-manager:
    GIT_TOKEN: "arn:aws:secretsmanager:us-east-1:636184159442:secret:james-test-WYYiCZ:GIT_TOKEN"

phases:
  install:
    on-failure: ABORT    

  pre_build:
    commands:
      - echo "Running Trufflehog scanning for secrets ..."      
      - docker run trufflesecurity/trufflehog:latest github --repo https://github.com/Uon-Social/Backend --token $GIT_TOKEN --no-verification --json
  
artifacts:
  files:
    - trufflehog.json