version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.11
    working_directory: ~/james
    steps:
      - checkout
      - run:
          name: View Fiiles in repo
          command: |
            ls -al
            echo '^^^The files in your repo^^^'
      - run:
          name: Load Docker image
          command: |
            docker load -i .
      - run:
          name: Run command inside container
          command: |
            docker run myimage /bin/sh -c "echo 'Hello, world!'"
