version: 2.1
jobs:
  build:
    docker:
      - image: python:3
    working_directory: ~/james
    steps:
      - checkout
      - run:
          name: Execute main.py
          command: |
            python main.py
  test:
    docker:
      - image: python:3
    working_directory: ~/james
    steps:
      - checkout
      - run:
          name: Execute main.py
          command: |
            python test.py
workflows:
  test_env:
    jobs:
      - build
      - test
        requires:
          - Fetch-Code
      - Hold-for-Approval
        type: approval
          requires:
            - build
            - test
      - deploy
        requires:
            - Hold-for-Approval