version: 2.1
jobs:
  run:
    docker:
      - image: python:3
    working_directory: ~/james
    steps:
      - checkout
      - run:
          name: Execute main.py
          command: |
            python main.py
  test:
    docker:
      - image: python:3
    working_directory: ~/james
    steps:
      - checkout
      - run:
          name: Execute main.py
          command: |
            python test.py
  build:
    docker: 
      - image: docker:20.10.22
    steps:
      - checkout
      - run:
          name: Run the docker release
          command: |
            docker run -v /var/run/docker.sock:/var/run/docker.sock docker:20.10.22
            apt-get update
            apt-get install docker.io            
  deploy:
    docker: 
      - image: alpine:3.15
    steps:
      - run:
          name: Done
          command: |
            echo "Done Deployment"

workflows:
  test_env:
    jobs:
      - run
      - test:
          requires:
            - run
      - build:
          requires:
            - run
            - test
      - Hold-for-Approval:
          type: approval
          requires:
            - run
            - test
            - build      
      - deploy:
          requires:
            - Hold-for-Approval