version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.11-git
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Build Docker image
          command: |
            docker build -t test .
  run:
    docker:
      - image: docker:20.10.11-git
    working_directory: ~/app
    steps:      
      - run:
          name: Run Docker
          command: |
            docker run test
  test:
    docker:
      - image: python:3
    working_directory: ~/app
    steps:      
      - run:
          name: Execute main.py
          command: |
            python test.py
  deploy:
    docker: 
      - image: alpine:3.15
    steps:
      - run:
          name: Done
          command: |
            echo "Done Deployment"

workflows:
  test_env:
    jobs:
      - build
      - run:
          requires:
            - build
      - test:
          requires:
            - build
            - run
      - Hold-for-Approval:
          type: approval
          requires:
            - build
            - run
            - test
      - deploy:
          requires:
            - Hold-for-Approval