version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.11
    working_directory: ~/james
    steps:
      - checkout
      - run:
          name: Execute main.py
          command: |
            python main.py
  test:
    docker:
      - image: docker:20.10.11
    working_directory: ~/james
    steps:
      - checkout
      - run:
          name: Execute main.py
          command: |
            python test.py

workflow:
  test_env:
    jobs:
      - build
      - test:
          requires:
            - build