version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.11
    working_directory: ~/james
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t test .
      - run:
          name: Run command inside container
          command: |
            docker run test